rtl/common/flopr.sv
rtl/common/mux2.sv
rtl/common/mux4.sv
rtl/controller/alu_dec.sv
rtl/controller/controller.sv
rtl/controller/main_dec.sv
rtl/datapath/dmem/addr_dec.sv
rtl/datapath/dmem/dmem_ctrl.sv
rtl/datapath/dmem/lane_dec.sv
rtl/datapath/dmem/read_shifter.sv
rtl/datapath/dmem/write_shifter.sv
rtl/datapath/alu.sv
rtl/datapath/datapath.sv
rtl/datapath/imm_dec.sv
rtl/datapath/instr_dec.sv
rtl/datapath/lower_ext.sv
rtl/datapath/pc_adder.sv
rtl/datapath/reg_file.sv
rtl/datapath/shifter.sv
rtl/datapath/sign_ext.sv
rtl/riscv.sv
dv/testbench.sv
dv/dmem.sv
dv/imem.sv
